### ISSUE TITLE
use javascript to start a new mock server - failed "unhandled 'err'r event"

### ISSUE THREAD

**Issue by hejunchen** [restbird/rest#2]
I am using the latest 3.6 restbird on my windows 10 machine.
I ran the following command to start a new Docker container:
```
docker run --rm -ti -d -p 8080:8080 -p 8088:8088 -p 8089:8089 -v D:\Applications\restbird-projects\my-first-project:/data/restbird restbird/rest
```
I tried to follow the tutorial online until I hit the error on Mock Server section with the following message in mock console:
```
I am Mocker Server Task
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8088
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Function.listen (/data/restbird/libraryJs/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/tmp/restbird/sandbox/mock346743243/restbird-mock.js:232:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I tried again using Golang in mock server and it is working fine.
I guess there is a bug in JavaScript version of Mock Server?

**Comment by chipnesh** [comment]
Faced the same problem. Any plans to fix this issue?
